on:
  push:
    branches:
      - main











jobs:
  build:
    runs-on: ubuntu-latest



    steps:
     
      - name: "printing name"
        run: echo "Andrew nazeh"
     
      - name: "printing name"
        run: echo "Andrew nazeh"




  
