on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest



    steps:
     
      - uses: actions/checkout@v3

      - name: "printing name"
        run: echo "Andrew nazeh"

      - name: "login docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: "build docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/java_app .
     
      - name: "push docker image "
        run: docker push ${{ secrets.DOCKER_USERNAME }}/java_app





  
