on:
  push:
    branches:
      - main











jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: "testing github action"
        run: pwd


      - name: "printing name"
        run: echo Andrew




  
